<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE sampletexts [
<!ELEMENT sampletexts (sample*)>

<!-- each file consists of several samples, which have a title taken from the BNC and text, encoded as par -->
<!ELEMENT sample (bnc:title,par)>
<!ATTLIST sample
          id ID #IMPLIED
          understood (yes|no) "yes">

<!ELEMENT bnc:title (#PCDATA)>
<!ATTLIST bnc:title
           bnc:id CDATA #IMPLIED
           bnc:n CDATA #IMPLIED
          xmlns:bnc CDATA #FIXED "http://info.ox.ac.uk:80/bnc/">

<!-- The text encoded in par contains text as well as one annotated name -->
<!ELEMENT par (#PCDATA|annot)*>

<!-- the annotated name can be of several tsemantic ypes. For Semeval 2007 only org (organisation) and location are used -->
<!ELEMENT annot  (nonapp|artefact|location|person|org|facility|animal|plant|natobject|substance|othertype)*>
<!ATTLIST annot
          id ID #IMPLIED>

<!-- locations have readings literal, metonymic or mixed. Metonymies have a reading type. Notes are free text comments for clarification only -->

<!ELEMENT location (#PCDATA)>
<!ATTLIST location
	  id ID #IMPLIED
	  reading (literal|metonymic|mixed|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|place-for-people|place-for-event|place-for-product|cap-country|othermet)    #IMPLIED
          notes CDATA #IMPLIED>

<!-- organisations have readings literal, metonymic or mixed. Metonymies have a reading type. Notes are free text comments for clarification only -->

<!ELEMENT org (#PCDATA)>
<!ATTLIST org
	  id ID #IMPLIED
	  reading (literal|metonymic|mixed|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|organisation-for-product|organisation-for-facility|organisation-for-members|organisation-for-index|organisation-for-event|othermet)    #IMPLIED
          notes CDATA #IMPLIED>

<!-- all otehr semantic types are not used in SemEval 2007 -->

<!ELEMENT artefact (#PCDATA)>
<!ATTLIST artefact
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|object-for-user|container-for-contents|part-for-whole|othermet|notagr) #IMPLIED
          notes CDATA #IMPLIED >

<!ELEMENT facility (#PCDATA)>
<!ATTLIST facility
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|facility-for-org|othermet|notagr) #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT nonapp (#PCDATA)>
<!ATTLIST nonapp
          id ID #IMPLIED>

<!ELEMENT person (#PCDATA)>
<!ATTLIST person
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
(object-for-representation|object-for-name|creator-for-creation|controller-for-controlled|othermet|notagr)
#IMPLIED
         notes CDATA #IMPLIED>

<!ELEMENT animal (#PCDATA)>
<!ATTLIST animal
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|animal-for-meat|animal-for-fur|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT plant (#PCDATA)>
<!ATTLIST plant
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|plant-for-product|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT natobject (#PCDATA)>
<!ATTLIST natobject
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|material-for-object|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT substance (#PCDATA)>
<!ATTLIST substance
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT othertype (#PCDATA)>
<!ATTLIST othertype
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!-- BNC entities are declared here; these entities can be replaced with Ascii-like signs via remove-characters.pl -->

<!ENTITY ast  "*">
<!ENTITY equals  "=">
<!ENTITY percnt "[percent]">
<!ENTITY plus  "+">
<!ENTITY sol  "/">
<!ENTITY half  "&#189;">
<!ENTITY horbar  "[horbar]">
<!ENTITY lowbar  "_">
<!ENTITY dash  "[dash]">
<!ENTITY Aacute   "&#193;">
<!ENTITY aacute   "&#225;">
<!ENTITY abreve   "[abreve]">
<!ENTITY Acirc   "&#194;">
<!ENTITY acirc   "&#226;">
<!ENTITY acute   "&#180;">
<!ENTITY AElig   "&#198;">
<!ENTITY aelig   "&#230;">
<!ENTITY agr   "[agr]" >
<!ENTITY Agrave   "&#192;" >
<!ENTITY agrave   "&#224;">
<!ENTITY Amacr   "[Amacr]">
<!ENTITY amacr   "[amacr]">
<!-- <!ENTITY amp   '&#38;'> -->
<!ENTITY ape   "[ape]">
<!ENTITY aogon   "[aogon]">
<!ENTITY Aring   "&#197;">
<!ENTITY aring   "&#229;">
<!ENTITY atilde   "&#227;" >
<!ENTITY Auml   "&#196;" >
<!ENTITY auml   "&#228;" >
<!ENTITY Bgr   "[Bgr]" >
<!ENTITY bgr   "[bgr]" >
<!ENTITY bquo   "&#96;" >
<!ENTITY bsol   "&#92;" >
<!ENTITY bull   "[bull]"  >
<!ENTITY cacute   "[cacute]"  >
<!ENTITY Ccaron   "[Ccaron]">
<!ENTITY ccaron   "[ccaron]"  >
<!ENTITY Ccedil   "&#199;" >
<!ENTITY ccedil   "&#231;">
<!ENTITY ccirc   "[ccirc]"  >
<!ENTITY cent   "&#162;">
<!ENTITY check   "[check]" >
<!ENTITY cir   "[cir]" >
<!ENTITY circ   "&#94;"  >
<!ENTITY commat   "@"  >
<!ENTITY copy   "&#169;" >
<!ENTITY darr   "[darr]" >
<!ENTITY dcaron   "[dcaron]" >
<!ENTITY deg   "&#176;">
<!ENTITY Dgr   "[Dgr]" >
<!ENTITY dgr   "[dgr]"  >
<!ENTITY die   "&#168;">
<!ENTITY divide   "&#247;"  >
<!ENTITY dollar   "&#36;">
<!ENTITY dstrok   "[dstrok]" >
<!ENTITY dtrif   "[dtrif]" >
<!ENTITY Eacute   "&#201;"  >
<!ENTITY eacute   "&#233;" >
<!ENTITY Ecaron   "[Ecaron]"  >
<!ENTITY ecaron   "[ecaron]" >
<!ENTITY Ecirc   "&#202;"  >
<!ENTITY ecirc   "&#234;" >
<!ENTITY eegr   "[eegr]"  >
<!ENTITY Egr   "[Egr]"  >
<!ENTITY egr   "[egr]" >
<!ENTITY Egrave   "&#200;" >
<!ENTITY egrave   "&#232;" >
<!ENTITY Emacr   "[Emacr]" >
<!ENTITY emacr   "[emacr]">
<!ENTITY eogon   "[eogon]"  >
<!ENTITY equo   '"' >
<!ENTITY eth   "&#240;"  >
<!ENTITY Euml   "&#203;"  >
<!ENTITY euml   "&#235;" >
<!ENTITY flat   "[flat]"  >
<!ENTITY formula   "[formula]"  >
<!ENTITY frac12   "&#189;">
<!ENTITY frac13   "[frac13]">
<!ENTITY frac14   "&#188;">
<!ENTITY frac15   "[frac15]">
<!ENTITY frac16   "[frac16]">
<!ENTITY frac17   "[frac17]">
<!ENTITY frac18   "[frac18]">
<!ENTITY frac19   "[frac19]">
<!ENTITY frac23   "[frac23]"   >
<!ENTITY frac25   "[frac25]">
<!ENTITY frac34   "&#190;">
<!ENTITY frac35   "[frac35]"  >
<!ENTITY frac38   "[frac38]">
<!ENTITY frac45   "[frac45]">
<!ENTITY frac47   "[frac47]" >
<!ENTITY frac56   "[frac56]" >
<!ENTITY frac58   "[frac58]">
<!ENTITY frac78   "[frac78]">
<!ENTITY ft   "'"   >
<!ENTITY ge   "[ge]"   >
<!ENTITY Ggr   "[Ggr]" >
<!ENTITY ggr   "[ggr]"  >
<!ENTITY grave   "&#96;"    >
<!ENTITY gt   ">" >
<!ENTITY Gt   "[Gt]" >
<!ENTITY hearts   "[hearts]">
<!ENTITY hellip   "[hellip]" >
<!ENTITY hstrok   "[hstrok]"   >
<!ENTITY Iacute   "&#205;"  >
<!ENTITY iacute   "&#237;"    >
<!ENTITY Icirc   "&#206;"  >
<!ENTITY icirc   "&#238;"  >
<!ENTITY iexcl   "&#161;" >
<!ENTITY igr   "[igr]"  >
<!ENTITY igrave   "&#236;" >
<!ENTITY imacr   "[imacr]"  >
<!ENTITY infin   "[infin]">
<!ENTITY ins   '"' >
<!ENTITY iquest   "&#191;" >
<!ENTITY Iuml   "&#207;"  >
<!ENTITY iuml   "&#239;"  >
<!ENTITY kgr   "[kgr]"    >
<!ENTITY khgr   "[khgr]"  >
<!ENTITY Lacute   "[Lacute]"  >
<!ENTITY lacute   "[lacute]"  >
<!ENTITY larr   "[larr]"  >
<!ENTITY lcub   "{" >
<!ENTITY le   "[le]"     >
<!ENTITY lgr   "[lgr]"  >
<!ENTITY lsqb   "["  >
<!ENTITY Lstrok   "[Lstrok]"   >
<!ENTITY lstrok   "[lstrok]" >
<!-- <!ENTITY lt   "<"   > -->
<!ENTITY Lt   "[Lt]"   >
<!ENTITY mdash   "[mdash]"  >
<!ENTITY Mgr   "[Mgr]" >
<!ENTITY mgr   "[mgr]"    >
<!ENTITY micro   "&#181;"   >
<!ENTITY middot   "&#183;"    >
<!ENTITY nacute   "[nacute]"     >
<!ENTITY natur   "[natur]"    >
<!ENTITY ncaron   "[ncaron]"   >
<!ENTITY ncedil   "[ncedil]"    >
<!ENTITY ndash   "[ndash]"   >
<!ENTITY ngr   "[ngr]"  >
<!ENTITY Ntilde   "&#209;"    >
<!ENTITY ntilde   "&#241;" >
<!ENTITY num   "#"    >
<!ENTITY Oacute   "&#211;"   >
<!ENTITY oacute   "&#243;" >
<!ENTITY Ocirc   "&#212;"  >
<!ENTITY ocirc   "&#244;"  >
<!ENTITY OElig   "[OElig]"  >
<!ENTITY oelig   "[oelig]" >
<!ENTITY Ogr   "[Ogr]" >
<!ENTITY ogr   "[ogr]" >
<!ENTITY ograve   "&#242;"  >
<!ENTITY OHgr   "[OHgr]"  >
<!ENTITY ohgr   "[ohgr]" >
<!ENTITY ohm   "[ohm]"  >
<!ENTITY omacr   "[omacr]" >
<!ENTITY Oslash   "&#216;" >
<!ENTITY oslash   "&#248;" >
<!ENTITY Otilde   "&#213;"  >
<!ENTITY otilde   "&#245;" >
<!ENTITY Ouml   "&#214;"  >
<!ENTITY ouml   "&#246;" >
<!ENTITY Pgr   "[Pgr]">
<!ENTITY pgr   "[pgr]" >
<!ENTITY PHgr   "[PHgr]"  >
<!ENTITY phgr   "[phgr]"  >
<!ENTITY plusmn   "&#177;"    >
<!ENTITY pound   "&#163;">
<!ENTITY Prime   "[Prime]"    >
<!ENTITY prime   "[prime]"   >
<!ENTITY PSgr   "[PSgr]"  >
<!ENTITY psgr   "[psgr]"    >
<!ENTITY quot   '"'    >
<!ENTITY racute   "[racute]"   >
<!ENTITY radic   "[radic]"    >
<!ENTITY rarr   "[rarr]"    >
<!ENTITY Rcaron   "[Rcaron]"     >
<!ENTITY rcaron   "[rcaron]"    >
<!ENTITY rcub   "}"    >
<!ENTITY reg   "&#174;"    >
<!ENTITY rehy   "&#173;"    >
<!ENTITY rgr   "[rgr]"    >
<!ENTITY rsqb   "]"    >
<!ENTITY Sacute   "[Sacute]" >
<!ENTITY sacute   "[sacute]"  >
<!ENTITY Scaron   "[Scaron]" >
<!ENTITY scaron   "[scaron]"  >
<!ENTITY Scedil   "[Scedil]" >
<!ENTITY scedil   "[scedil]"  >
<!ENTITY scirc   "[scirc]" >
<!ENTITY sect   "&#167;" >
<!ENTITY Sgr   "[Sgr]"  >
<!ENTITY sgr   "[sgr]"  >
<!ENTITY sharp   "[sharp]"  >
<!ENTITY sim   "[sim]"  >
<!ENTITY shilling   "/-"  >
<!ENTITY sup1   "&#185;" >
<!ENTITY sup2   "&#178;"  >
<!ENTITY sup3   "&#179;" >
<!ENTITY szlig   "&#223;"  >
<!ENTITY tcaron   "[tcaron]" >
<!ENTITY tcedil   "[tcedil]"  >
<!ENTITY tgr   "[tgr]" >
<!ENTITY THgr   "[THgr]"  >
<!ENTITY thgr   "[thgr]"  >
<!ENTITY THORN   "&#222;" >
<!ENTITY thorn   "&#254;" >
<!ENTITY tilde   "&#126;">
<!ENTITY times   "&#215;" >
<!ENTITY trade   "[trade]" >
<!ENTITY Uacute   "&#218;" >
<!ENTITY uacute   "&#250;" >
<!ENTITY Ucirc   "&#219;" >
<!ENTITY ucirc   "&#251;"  >
<!ENTITY Ugr   "[Ugr]"  >
<!ENTITY ugr   "[ugr]" >
<!ENTITY ugrave   "&#249;"  >
<!ENTITY umacr   "[umacr]" >
<!ENTITY uml   "&#168;" >
<!ENTITY uring   "[uring]"  >
<!ENTITY Uuml   "&#220;" >
<!ENTITY uuml   "&#252;">
<!ENTITY verbar   "|" >
<!ENTITY wcirc   "[wcirc]" >
<!ENTITY xgr   "[xgr]">
<!ENTITY yacute   "&#253;"  >
<!ENTITY Ycirc   "[Ycirc]">
<!ENTITY ycirc   "[ycirc]"  >
<!ENTITY yen   "&#165;" >
<!ENTITY Yuml   "[Yuml]"  >
<!ENTITY yuml   "&#255;" >
<!ENTITY zacute   "[zacute]"  >
<!ENTITY Zcaron   "[Zcaron]"  >
<!ENTITY zcaron   "[zcaron]" >
<!ENTITY zdot   "[zdot]"  >
<!ENTITY Zgr   "[Zgr]"  >
<!ENTITY zgr   "[zgr]" >
]>

<sampletexts> 

<sample id="samp1">
<bnc:title> Computergram international </bnc:title>
<par>
<annot><location reading="literal"> US </location></annot> FEDERAL TRADE COMMISSION REVIEWS STAFF REPORT ON ANTI-TRUST ALLEGATIONS 
The US Federal Trade Commission is reviewing a new staff report on the anti-trust allegations against Microsoft Corp, but a decision on the matter probably is still weeks away, lawyers familiar with the case told the Wall Street Journal: with a two-to-two vote in February, the commission didn't accept staff recommendations to seek an injunction preventing the company from using its market power to engage in allegedly unfair competitive practices; after the tied vote, the commissioners asked for more information in an effort to resolve the deadlock; the status report, which was delivered to commissioners last week, provides additional support for the staff's call for action. 
</par> 
</sample> 

<sample id="samp2">
<bnc:title> Palestine and Israel </bnc:title>
<par>
The influx of cheap Arab labour from the occupied territories allowed the Israeli economy to expand rapidly after 1967, pushing unskilled Jewish labour into higher grade work. 
The shift in the labour pattern significantly reduced the tensions between the European and non-European and largely unskilled Jewish elements in Israel which during the 1960s was becoming a serious social and political issue since the latter grew faster demographically than the former. 
Overall, <annot><location reading="metonymic" metotype="place-for-people" notes="underspecified between OFF, POP"> Israel </location></annot>'s absorption of over 100,000 Palestinians as casual labourers created a feeling of weakness and helplessness in the Palestinian community, and of success and power within the Israeli economy. 
Since the territories were captive, Israel could develop them as its second largest export market (after the United States), with an export value of &dollar;800 million annually by 1986. 
</par> 
</sample> 

<sample id="samp3">
<bnc:title> Migrations: travels of a naturalist </bnc:title>
<par>
Why don't we do it? &equo; and we all agreed rather tentatively that it might be a good idea. 
Well, unlike many of the promises that are made over the clinking of glasses and in the glow of a few drinks, and despite the fact that Pam and Tony lived near Thurso in the north of Scotland, Wendy was working in Bristol and I lived in Shetland, we got in touch later and laid firm plans for a trip to Lapland. 
We decided that we would like to spend much of our available time in the far north, beyond the Arctic Circle so, taking turns at driving and stopping only for fuel and occasional snacks, we thrashed on up the &bquo; spine &equo; of <annot><location reading="literal"> Norway </location></annot> through spectacular mountain scenery to Trondheim. 
Much of the country was wooded and the birds were not too obvious. 
</par> 
</sample> 

<sample id="samp4">
<bnc:title> Accountancy </bnc:title>
<par>
I'd be somewhat hopeful we might get something on it. &equo; 
If that's all we get, British industry won't be terribly happy about it. 
ACT is discriminatory, and it discriminates against the kind of companies that generally speaking are good for <annot><location reading="metonymic" metotype="othermet" notes="British economy"> Britain </location></annot> 
Michael Heseltine: Talking to the Chancellor 
</par> 
</sample> 

<sample id="samp5">
<bnc:title> Markets and dealers &lsqb;2/4&rsqb; </bnc:title>
<par>
Thus the Long Gilt suffered a mild setback in 1988 and 1989 as the public sector finances moved from deficit to surplus and the Treasury instituted a &quot; buy-back &quot; programme for long-dated gilts. 
Partly due to this, the long end of the yield curve has been rather stable in the UK, and the need to hedge at this end of the term structure was diminished. 
However, turnover increased in 1990 due to <annot><location reading="literal"> UK </location></annot> entry into the European Exchange Rate Mechanism, which implied a shift in longer term inflationary expectations and a fortiori long rates of interest, combined with the fact that the public sector finances had moved back into deficit. 
The German Bund contract was strong from the outset, probably due to the previously unsatisfied demand for derivatives based on German bonds, but this has been strengthened considerably by the reunification of Germany and the resulting uncertainty about long term yields on German paper. 
</par> 
</sample> 

<sample id="samp6">
<bnc:title> The Belfast Telegraph May 1993 </bnc:title>
<par>
This time Zimbabwe made the most of it, and midway through the half wing Victor Olonga pounced for a try. 
That came after full-back Mike Rayer had dropped a huge up and under from Craig Brown beneath his posts and Olonga just won the touch ahead of Hill. 
The final quarter was virtually all <annot><location reading="metonymic" metotype="place-for-people" notes="ORG, sports, team"> Zimbabwe </location></annot>, although lock Phil Davies was able to charge through for Wales' fourth try seven minutes from time, which Jenkins again converted. 
</par> 
</sample> 

<sample id="samp7">
<bnc:title> The hundred years war </bnc:title>
<par>
Some of the books which he is known to have possessed, which included Christine de Pisan's Letter of Othea to Hector, a didactic work for knights, reinforce this view. 
At the same time Fastolf s attitude to the practicalities of war reflect a hardheadedness which was essentially of this world: the plan which he drew up in 1435 favouring a &bquo; tough &equo; approach to the war made little concession to romantic ideas of chivalry which would influence a knight's conduct in war. 
His long career in <annot><location reading="literal"> France </location></annot> which led him to hold high military and administrative posts, as well as amassing a fortune through the capture of prisoners in battle, the seizing of property and the exploitation of estates, shows him to have been a &bquo; realistic &equo; person in all that he did. 
As often the case, Froissart had a story which illustrates this point. 
</par> 
</sample> 

<sample id="samp8">
<bnc:title> Man at the sharp end </bnc:title>
<par>
It was alleged by Clasper that the foreman had his knife in the young kid who was only doing his job. 
&bquo; The foreman is out to get him &equo; was the expression making the departmental rounds. 
Clasper and the conspirators timed the third offence to coincide with the visit to the <annot><location reading="literal"> UK </location></annot> of the President and Chief Executive Officer of United Motors, Nate Cocello, as this would provide maximum publicity to the planned strike. 
An attempt would then be made to drag Cocello into the dispute by Clasper making a public appeal to the President to reinstate the sacked shop steward over the heads of plant and divisional management. 
</par> 
</sample> 

<sample id="samp9">
<bnc:title> Rethinking the Russian revolution </bnc:title>
<par>
The xenophobia and repression associated with Stalin's last years and the culmination of the personality cult belied the Soviet Union's internationalist pretensions. 
Even those who saw the extension of Moscow's control over her eastern European neighbours as primarily a response to American expansion objected to the oppressive form of Soviet rule. 
The successive rebellions against Soviet-backed regimes &mdash; in <annot><location reading="literal"> East Germany </location></annot> in 1953, in Poland and Hungary in 1956, in Czechoslovakia in 1968 and in Poland in the early 1980s &mdash; progressively undermined the allegiance of foreign radicals to the USSR. 
This bristling empire built on the bones of peasants and political prisoners and denying the most fundamental rights to the workers themselves seemed more and more a mere mirror image of the capitalist system rejected by western radicals. 
</par> 
</sample> 

<sample id="samp10">
<bnc:title> Keesings Contemporary Archives. November 1991 </bnc:title>
<par>
He had based his electoral platform on the need for better relations with the United States. 
Political observers felt, however, that difficulties could still arise with the USA, because of his publicly expressed view that Japan's trade surplus was a &quot; fundamentally insoluble problem &quot; caused by unstoppable world demand for superior Japanese products, and would remain impervious to import tariffs or even major currency shifts. 
Miyazawa's recent calls for a period of renewed economic growth in <annot><location reading="literal"> Japan </location></annot> and for a cut in Japanese interest rates (implying a weakening of the yen and a growth in the trade surplus) were also received with concern in the USA. 
Miyazawa had also called during his election campaign for the political rehabilitation and &quot; purification &quot; of Japanese politicians who had been implicated, like himself, in the financial scandals of recent years. 
</par> 
</sample> 

<sample id="samp11">
<bnc:title> Keesings Contemporary Archives. April 1991 </bnc:title>
<par>
The Kabul regime responded by reinforcing the garrison's 3,000-4,000 regular troops and by launching a high-altitude bombing campaign; Kabul-based Scud-missiles were also fired at rebel positions. 
An assortment of mujaheddin guerrillas were involved in the offensive, including supporters of Gulbuddin Hekmatyar's fundamentalist Hezb-e Islami and Jalaluddin Haqqani's rival Hezb-e Islami (Yunis Khan faction). 
The rebels also reportedly received logistical support from the <annot><location reading="literal"> United States </location></annot> Central Intelligence Agency (CIA) and its Pakistani counterpart, the Inter Services Intelligence (ISI). 
The Afghan government claimed that artillery and infantry units of the Pakistan army had actually entered the battle at a decisive stage in late March. 
</par> 
</sample> 

<sample id="samp12">
<bnc:title> BBC Wildlife </bnc:title>
<par>
Go back and think again, they said, this time with the emphasis on energy efficiency and renewables. 
He won't, of course; as an oil man, he probably can't. 
But it's encouraging that so many scientists, politicians and (of late) influential business people have been making it unmistakably clear to White House officials that the <annot><location reading="metonymic" metotype="place-for-people" notes="OFF"> US </location></annot> position on global warming and the whole Earth Summit process absolutely stinks. 
There's really not much point advocating a &bquo; New World Order &equo; if there's no world left in which to establish that order. 
</par> 
</sample> 

<sample id="samp13">
<bnc:title> Recorded Speech </bnc:title>
<par>
And 
Anthony and his, Anthony and his colleagues are going around, is it just England or are you going to Scotland and Wales as well? 
The whole of <annot><location reading="literal"> Great Britain </location></annot>, so Northern, Northern Ireland as well. 
The whole of British Isles, right, erm in various sort of settings, different places, you're going to a school aren't you tomorrow 
</par> 
</sample> 

<sample id="samp14">
<bnc:title> &lsqb;Independent, electronic edition of 19891012; Homematerial&rsqb; </bnc:title>
<par>
They believe that the current slaughter policy is a political expedient designed to allow ministers to show that they are doing something to curb food poisoning. 
The measures have little relevance to public health. 
The race is now on to show that the Government is wrong before the last bird in the <annot><location reading="literal"> UK </location></annot> is slaughtered. 
Even now it might be too late: imports are rushing in to replace the shortfall. 
</par> 
</sample> 

<sample id="samp15">
<bnc:title> Twentieth century British history </bnc:title>
<par>
The scale of <annot><location reading="literal"> Britain </location></annot>'s overseas government expenditure was a source of intense debate at the time, and has remained a source of criticism of the Attlee government's policies. 
Was this a case of folie de grandeur, in which Britain's economic recovery was sacrificed to anachronistic (and unsocialist?) attempts to retain a great power stance in the world? 
</par> 
</sample> 

<sample id="samp16">
<bnc:title> &lsqb;Title unknown/unassigned&rsqb; </bnc:title>
<par>
Already, the Scots have seen Australia at close quarters in last week's Canberra Tournament, where the Wallabies reached the semi-final, while, earlier in the season, they faced a number of possible participants in the colours of Queensland in Dubai. 
This week, in the inaugural Fiji International Sevens, the Scots will be able to devote further studies to the Australians and get their first glimpse of Tonga, against whom they are also drawn in the Hong Kong Sevens. 
The trip to the colony next week will enable them to do their homework, too, on <annot><location reading="metonymic" metotype="place-for-people" notes="ORG, sports, team"> Argentina </location></annot> and Italy. 
Thus only Taiwan from the Scots' pool for the Murrayfield event will not be seen in the flesh, although Scotland's sevens coaches, Douglas Morgan and John Jeffrey, will doubtless seek videotape of the tournament in Sicily last summer from which the Taiwanese qualified. 
</par> 
</sample> 

<sample id="samp17">
<bnc:title> &lsqb;Title unknown/unassigned&rsqb; </bnc:title>
<par>
THE most coveted trophy in North-East athletics history is to be auctioned at Christie's in London a week today. 
Organisers of <annot><location reading="literal"> Britain </location></annot>'s oldest road race, the annual New Year's Day Morpeth to Newcastle event, will be surprised to discover that the original prize is up for sale at a special sporting memorabilia auction. 
It was presented, to Darlington Harrier Andy Campbell, when the race was established as an open event in 1904 and given to Duncan McLeod-Wright to keep when the Scottish runner became the first man to win three times, in 1929. 
</par> 
</sample> 

<sample id="samp18">
<bnc:title> Today </bnc:title>
<par>
Unless you do I can not watch you. 
You are a god here. &equo; 
Bill, 76, asked Street chiefs to investigate and they discovered that episodes of the popular show screened in Britain five years ago are now topping the ratings in <annot><location reading="literal"> Thailand </location></annot> and they have made Percy a national hero. 
Startled Bill, 76, said: &bquo; At first I thought what a damned cheek sending me an electric bill. 
</par> 
</sample> 

<sample id="samp19">
<bnc:title> The economist </bnc:title>
<par>
FROM OUR SOUTH-EAST ASIA CORRESPONDENT 
LIKE Korea, Singapore has economic problems that most other countries can only envy. 
Last year real GNP grew by 8.5%, and inflation was only 3.4%, lower than anywhere in Asia except <annot><location reading="literal"> Japan </location></annot> and Malaysia. 
Growth this year is expected to be a tolerable 5%. 
</par> 
</sample> 

<sample id="samp20">
<bnc:title> Keesings Contemporary Archives. April 1992 </bnc:title>
<par>
Jiang's visit was the first to Japan by a CCP general secretary since 1983. 
Release of details on political prisoner 
On April 7 the government disclosed information about one of <annot><location reading="literal"> China </location></annot>'s best-known political prisoners, Wei Jingsheng. 
One of the leaders of the Beijing Spring movement in 1978-79 which had created a &quot; Democracy Wall &quot; in the capital, Wei had been arrested in 1979 and sentenced to 15 years in prison &lsqb; see pp. 30495-96 &rsqb;. 
</par> 
</sample> 

<sample id="samp21">
<bnc:title> Capitalism since 1945 </bnc:title>
<par>
In addition, the very high demand in the early seventies may well have pushed up investment goods prices especially fast. 
It is certainly the case that the rapid increase in materials prices would tend to push up investment goods prices (which include an imported materials element) faster than output prices (which are defined to exclude the impact of import prices). 
Finally, some part of the fall in the output-capital ratio in the <annot><location reading="literal"> United States </location></annot> after 1966 must have reflected the decreasing capacity utilization. 
While it is impossible to measure precisely the influence of these factors, they all probably contributed to the falling output-capital ratio and the consequent decline in the profit rate. 
</par> 
</sample> 

<sample id="samp22">
<bnc:title> Computergram international </bnc:title>
<par>
FUJITSU SHOWS OFF TECHNOLOGIES DEVELOPED WITH SINGAPORE &hellip; 
Fujtisu Ltd is to demonstrate advanced information and communications systems at Asian Telecom 93, to be held in Singapore from May 17 to 22. 
The exhibition will include various technologies on which Fujitsu and the <annot><location reading="literal"> Singapore </location></annot> government have been working as part of the IT2000 plan, Singapore's comprehensive computing plan for the twenty-first century, which include south-east Asia's first B-ISDN service. 
B-ISDN field trials, conducted jointly by Fujtisu and Singapore, began in October 1992. 
</par> 
</sample> 

<sample id="samp23">
<bnc:title> The daily mirror </bnc:title>
<par>
Knives were drawn during his two years with PSV in Holland. 
Now Robson's jeered off at Sporting Lisbon for losing a UEFA Cup tie. 
He's on &pound;300,000 in <annot><location reading="literal"> Portugal </location></annot>, but for how long? 
Get yourself an air ticket, Bob! 
</par> 
</sample> 

<sample id="samp24">
<bnc:title> Keesings Contemporary Archives. July 1992 </bnc:title>
<par>
Group of 24 meeting 
Representatives of the Group of 24 (G-24) industrialized countries, which co-ordinated aid for eastern Europe and former Soviet Asia, met in the Albanian capital, Tirana, on July 22 in order to discuss with the Albanian authorities and international financial institutions how aid to Albania might be accelerated. 
The G-24 group expressed readiness to provide <annot><location reading="metonymic" metotype="place-for-people" notes="underspecified between OFF, ORG, POP"> Albania </location></annot> with food aid until the 1993 harvest, and beyond if necessary. 
Italy was a major donor among European countries and Greece announced that it would make available US&dollar;70,000,000 for agricultural development, which was given high priority. 
</par> 
</sample> 

<sample id="samp25">
<bnc:title> Consumption, identity and style </bnc:title>
<par>
(And when they reappeared on screen, another wave of the plastic wands did the trick again.) 
What no one had to do in all this was think. 