<?xml version="1.0" encoding="ISO-8859-1"?> 
<!DOCTYPE sampletexts [
<!ELEMENT sampletexts (sample*)>

<!-- each file consists of several samples, which have a title taken from the BNC and text, encoded as par -->
<!ELEMENT sample (bnc:title,par)>
<!ATTLIST sample
          id ID #IMPLIED
          understood (yes|no) "yes">

<!ELEMENT bnc:title (#PCDATA)>
<!ATTLIST bnc:title
           bnc:id CDATA #IMPLIED
           bnc:n CDATA #IMPLIED
          xmlns:bnc CDATA #FIXED "http://info.ox.ac.uk:80/bnc/">

<!-- The text encoded in par contains text as well as one annotated name -->
<!ELEMENT par (#PCDATA|annot)*>

<!-- the annotated name can be of several tsemantic ypes. For Semeval 2007 only org (organisation) and location are used -->
<!ELEMENT annot  (nonapp|artefact|location|person|org|facility|animal|plant|natobject|substance|othertype)*>
<!ATTLIST annot
          id ID #IMPLIED>

<!-- locations have readings literal, metonymic or mixed. Metonymies have a reading type. Notes are free text comments for clarification only -->

<!ELEMENT location (#PCDATA)>
<!ATTLIST location
	  id ID #IMPLIED
	  reading (literal|metonymic|mixed|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|place-for-people|place-for-event|place-for-product|cap-country|othermet)    #IMPLIED
          notes CDATA #IMPLIED>

<!-- organisations have readings literal, metonymic or mixed. Metonymies have a reading type. Notes are free text comments for clarification only -->

<!ELEMENT org (#PCDATA)>
<!ATTLIST org
	  id ID #IMPLIED
	  reading (literal|metonymic|mixed|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|organisation-for-product|organisation-for-facility|organisation-for-members|organisation-for-index|organisation-for-event|othermet)    #IMPLIED
          notes CDATA #IMPLIED>

<!-- all otehr semantic types are not used in SemEval 2007 -->

<!ELEMENT artefact (#PCDATA)>
<!ATTLIST artefact
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|object-for-user|container-for-contents|part-for-whole|othermet|notagr) #IMPLIED
          notes CDATA #IMPLIED >

<!ELEMENT facility (#PCDATA)>
<!ATTLIST facility
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype (object-for-representation|object-for-name|facility-for-org|othermet|notagr) #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT nonapp (#PCDATA)>
<!ATTLIST nonapp
          id ID #IMPLIED>

<!ELEMENT person (#PCDATA)>
<!ATTLIST person
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
(object-for-representation|object-for-name|creator-for-creation|controller-for-controlled|othermet|notagr)
#IMPLIED
         notes CDATA #IMPLIED>

<!ELEMENT animal (#PCDATA)>
<!ATTLIST animal
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|animal-for-meat|animal-for-fur|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT plant (#PCDATA)>
<!ATTLIST plant
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|plant-for-product|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT natobject (#PCDATA)>
<!ATTLIST natobject
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|material-for-object|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT substance (#PCDATA)>
<!ATTLIST substance
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!ELEMENT othertype (#PCDATA)>
<!ATTLIST othertype
	  id ID #IMPLIED
	  reading (homonym|literal|metonymic|mixed|other|notagr|unknown) #IMPLIED
          metotype
	  (object-for-representation|object-for-name|othermet|notagr)    #IMPLIED
          notes CDATA #IMPLIED>

<!-- BNC entities are declared here; these entities can be replaced with Ascii-like signs via remove-characters.pl -->

<!ENTITY ast  "*">
<!ENTITY equals  "=">
<!ENTITY percnt "[percent]">
<!ENTITY plus  "+">
<!ENTITY sol  "/">
<!ENTITY half  "&#189;">
<!ENTITY horbar  "[horbar]">
<!ENTITY lowbar  "_">
<!ENTITY dash  "[dash]">
<!ENTITY Aacute   "&#193;">
<!ENTITY aacute   "&#225;">
<!ENTITY abreve   "[abreve]">
<!ENTITY Acirc   "&#194;">
<!ENTITY acirc   "&#226;">
<!ENTITY acute   "&#180;">
<!ENTITY AElig   "&#198;">
<!ENTITY aelig   "&#230;">
<!ENTITY agr   "[agr]" >
<!ENTITY Agrave   "&#192;" >
<!ENTITY agrave   "&#224;">
<!ENTITY Amacr   "[Amacr]">
<!ENTITY amacr   "[amacr]">
<!-- <!ENTITY amp   '&#38;'> -->
<!ENTITY ape   "[ape]">
<!ENTITY aogon   "[aogon]">
<!ENTITY Aring   "&#197;">
<!ENTITY aring   "&#229;">
<!ENTITY atilde   "&#227;" >
<!ENTITY Auml   "&#196;" >
<!ENTITY auml   "&#228;" >
<!ENTITY Bgr   "[Bgr]" >
<!ENTITY bgr   "[bgr]" >
<!ENTITY bquo   "&#96;" >
<!ENTITY bsol   "&#92;" >
<!ENTITY bull   "[bull]"  >
<!ENTITY cacute   "[cacute]"  >
<!ENTITY Ccaron   "[Ccaron]">
<!ENTITY ccaron   "[ccaron]"  >
<!ENTITY Ccedil   "&#199;" >
<!ENTITY ccedil   "&#231;">
<!ENTITY ccirc   "[ccirc]"  >
<!ENTITY cent   "&#162;">
<!ENTITY check   "[check]" >
<!ENTITY cir   "[cir]" >
<!ENTITY circ   "&#94;"  >
<!ENTITY commat   "@"  >
<!ENTITY copy   "&#169;" >
<!ENTITY darr   "[darr]" >
<!ENTITY dcaron   "[dcaron]" >
<!ENTITY deg   "&#176;">
<!ENTITY Dgr   "[Dgr]" >
<!ENTITY dgr   "[dgr]"  >
<!ENTITY die   "&#168;">
<!ENTITY divide   "&#247;"  >
<!ENTITY dollar   "&#36;">
<!ENTITY dstrok   "[dstrok]" >
<!ENTITY dtrif   "[dtrif]" >
<!ENTITY Eacute   "&#201;"  >
<!ENTITY eacute   "&#233;" >
<!ENTITY Ecaron   "[Ecaron]"  >
<!ENTITY ecaron   "[ecaron]" >
<!ENTITY Ecirc   "&#202;"  >
<!ENTITY ecirc   "&#234;" >
<!ENTITY eegr   "[eegr]"  >
<!ENTITY Egr   "[Egr]"  >
<!ENTITY egr   "[egr]" >
<!ENTITY Egrave   "&#200;" >
<!ENTITY egrave   "&#232;" >
<!ENTITY Emacr   "[Emacr]" >
<!ENTITY emacr   "[emacr]">
<!ENTITY eogon   "[eogon]"  >
<!ENTITY equo   '"' >
<!ENTITY eth   "&#240;"  >
<!ENTITY Euml   "&#203;"  >
<!ENTITY euml   "&#235;" >
<!ENTITY flat   "[flat]"  >
<!ENTITY formula   "[formula]"  >
<!ENTITY frac12   "&#189;">
<!ENTITY frac13   "[frac13]">
<!ENTITY frac14   "&#188;">
<!ENTITY frac15   "[frac15]">
<!ENTITY frac16   "[frac16]">
<!ENTITY frac17   "[frac17]">
<!ENTITY frac18   "[frac18]">
<!ENTITY frac19   "[frac19]">
<!ENTITY frac23   "[frac23]"   >
<!ENTITY frac25   "[frac25]">
<!ENTITY frac34   "&#190;">
<!ENTITY frac35   "[frac35]"  >
<!ENTITY frac38   "[frac38]">
<!ENTITY frac45   "[frac45]">
<!ENTITY frac47   "[frac47]" >
<!ENTITY frac56   "[frac56]" >
<!ENTITY frac58   "[frac58]">
<!ENTITY frac78   "[frac78]">
<!ENTITY ft   "'"   >
<!ENTITY ge   "[ge]"   >
<!ENTITY Ggr   "[Ggr]" >
<!ENTITY ggr   "[ggr]"  >
<!ENTITY grave   "&#96;"    >
<!ENTITY gt   ">" >
<!ENTITY Gt   "[Gt]" >
<!ENTITY hearts   "[hearts]">
<!ENTITY hellip   "[hellip]" >
<!ENTITY hstrok   "[hstrok]"   >
<!ENTITY Iacute   "&#205;"  >
<!ENTITY iacute   "&#237;"    >
<!ENTITY Icirc   "&#206;"  >
<!ENTITY icirc   "&#238;"  >
<!ENTITY iexcl   "&#161;" >
<!ENTITY igr   "[igr]"  >
<!ENTITY igrave   "&#236;" >
<!ENTITY imacr   "[imacr]"  >
<!ENTITY infin   "[infin]">
<!ENTITY ins   '"' >
<!ENTITY iquest   "&#191;" >
<!ENTITY Iuml   "&#207;"  >
<!ENTITY iuml   "&#239;"  >
<!ENTITY kgr   "[kgr]"    >
<!ENTITY khgr   "[khgr]"  >
<!ENTITY Lacute   "[Lacute]"  >
<!ENTITY lacute   "[lacute]"  >
<!ENTITY larr   "[larr]"  >
<!ENTITY lcub   "{" >
<!ENTITY le   "[le]"     >
<!ENTITY lgr   "[lgr]"  >
<!ENTITY lsqb   "["  >
<!ENTITY Lstrok   "[Lstrok]"   >
<!ENTITY lstrok   "[lstrok]" >
<!-- <!ENTITY lt   "<"   > -->
<!ENTITY Lt   "[Lt]"   >
<!ENTITY mdash   "[mdash]"  >
<!ENTITY Mgr   "[Mgr]" >
<!ENTITY mgr   "[mgr]"    >
<!ENTITY micro   "&#181;"   >
<!ENTITY middot   "&#183;"    >
<!ENTITY nacute   "[nacute]"     >
<!ENTITY natur   "[natur]"    >
<!ENTITY ncaron   "[ncaron]"   >
<!ENTITY ncedil   "[ncedil]"    >
<!ENTITY ndash   "[ndash]"   >
<!ENTITY ngr   "[ngr]"  >
<!ENTITY Ntilde   "&#209;"    >
<!ENTITY ntilde   "&#241;" >
<!ENTITY num   "#"    >
<!ENTITY Oacute   "&#211;"   >
<!ENTITY oacute   "&#243;" >
<!ENTITY Ocirc   "&#212;"  >
<!ENTITY ocirc   "&#244;"  >
<!ENTITY OElig   "[OElig]"  >
<!ENTITY oelig   "[oelig]" >
<!ENTITY Ogr   "[Ogr]" >
<!ENTITY ogr   "[ogr]" >
<!ENTITY ograve   "&#242;"  >
<!ENTITY OHgr   "[OHgr]"  >
<!ENTITY ohgr   "[ohgr]" >
<!ENTITY ohm   "[ohm]"  >
<!ENTITY omacr   "[omacr]" >
<!ENTITY Oslash   "&#216;" >
<!ENTITY oslash   "&#248;" >
<!ENTITY Otilde   "&#213;"  >
<!ENTITY otilde   "&#245;" >
<!ENTITY Ouml   "&#214;"  >
<!ENTITY ouml   "&#246;" >
<!ENTITY Pgr   "[Pgr]">
<!ENTITY pgr   "[pgr]" >
<!ENTITY PHgr   "[PHgr]"  >
<!ENTITY phgr   "[phgr]"  >
<!ENTITY plusmn   "&#177;"    >
<!ENTITY pound   "&#163;">
<!ENTITY Prime   "[Prime]"    >
<!ENTITY prime   "[prime]"   >
<!ENTITY PSgr   "[PSgr]"  >
<!ENTITY psgr   "[psgr]"    >
<!ENTITY quot   '"'    >
<!ENTITY racute   "[racute]"   >
<!ENTITY radic   "[radic]"    >
<!ENTITY rarr   "[rarr]"    >
<!ENTITY Rcaron   "[Rcaron]"     >
<!ENTITY rcaron   "[rcaron]"    >
<!ENTITY rcub   "}"    >
<!ENTITY reg   "&#174;"    >
<!ENTITY rehy   "&#173;"    >
<!ENTITY rgr   "[rgr]"    >
<!ENTITY rsqb   "]"    >
<!ENTITY Sacute   "[Sacute]" >
<!ENTITY sacute   "[sacute]"  >
<!ENTITY Scaron   "[Scaron]" >
<!ENTITY scaron   "[scaron]"  >
<!ENTITY Scedil   "[Scedil]" >
<!ENTITY scedil   "[scedil]"  >
<!ENTITY scirc   "[scirc]" >
<!ENTITY sect   "&#167;" >
<!ENTITY Sgr   "[Sgr]"  >
<!ENTITY sgr   "[sgr]"  >
<!ENTITY sharp   "[sharp]"  >
<!ENTITY sim   "[sim]"  >
<!ENTITY shilling   "/-"  >
<!ENTITY sup1   "&#185;" >
<!ENTITY sup2   "&#178;"  >
<!ENTITY sup3   "&#179;" >
<!ENTITY szlig   "&#223;"  >
<!ENTITY tcaron   "[tcaron]" >
<!ENTITY tcedil   "[tcedil]"  >
<!ENTITY tgr   "[tgr]" >
<!ENTITY THgr   "[THgr]"  >
<!ENTITY thgr   "[thgr]"  >
<!ENTITY THORN   "&#222;" >
<!ENTITY thorn   "&#254;" >
<!ENTITY tilde   "&#126;">
<!ENTITY times   "&#215;" >
<!ENTITY trade   "[trade]" >
<!ENTITY Uacute   "&#218;" >
<!ENTITY uacute   "&#250;" >
<!ENTITY Ucirc   "&#219;" >
<!ENTITY ucirc   "&#251;"  >
<!ENTITY Ugr   "[Ugr]"  >
<!ENTITY ugr   "[ugr]" >
<!ENTITY ugrave   "&#249;"  >
<!ENTITY umacr   "[umacr]" >
<!ENTITY uml   "&#168;" >
<!ENTITY uring   "[uring]"  >
<!ENTITY Uuml   "&#220;" >
<!ENTITY uuml   "&#252;">
<!ENTITY verbar   "|" >
<!ENTITY wcirc   "[wcirc]" >
<!ENTITY xgr   "[xgr]">
<!ENTITY yacute   "&#253;"  >
<!ENTITY Ycirc   "[Ycirc]">
<!ENTITY ycirc   "[ycirc]"  >
<!ENTITY yen   "&#165;" >
<!ENTITY Yuml   "[Yuml]"  >
<!ENTITY yuml   "&#255;" >
<!ENTITY zacute   "[zacute]"  >
<!ENTITY Zcaron   "[Zcaron]"  >
<!ENTITY zcaron   "[zcaron]" >
<!ENTITY zdot   "[zdot]"  >
<!ENTITY Zgr   "[Zgr]"  >
<!ENTITY zgr   "[zgr]" >
]>

<sampletexts xmlns:bnc="http://www.w3.org/TR/html4/">

<sample id="samp1001">
<bnc:title> Modern catholicism: Vatican II and after </bnc:title>
<par>
Note
Gustavo Gutierrez has stressed the importance of this remark for <annot><location reading="metonymic" metotype="place-for-people" notes="POP"> Latin America </location></annot>, adding: &bquo; The preference, the predilection (not exclusive, let's be clear) for the poor is not opposed in the mind of the Pope to his universal mission; on the contrary it makes his universal mission quite concrete &equo; (Alberigo and Jossua, pp. 239, 240).
</par>
<label>met</label>
</sample>

<sample id="samp1002">
<bnc:title> Contemporary Britain: A Geographical Perspective </bnc:title>
<par>
Kondratieff presented few data for growth from 1789 to 1814 from countries other than Britain because they had little growth to analyse.
Parts of Belgium, Germany and France were economically active, but real growth came with the mid-century period of railway building.
&bquo; It seems possible to place France in the company of those countries &mdash; <annot><location reading="literal"> Germany </location></annot> and the US included &mdash; which at mid century experienced a &bquo; railway Kondratieff &equo; with emphatic growth-industry capabilities &equo; (Trebilcock, 1981).
Having achieved modern technological growth in the period 1849 to 1873, several of these countries then consolidated their competitive position during the &bquo; Victorian depression &equo; of the 1880s.
</par>
<label>lit</label>
</sample>

<sample id="samp1004">
<bnc:title> Keesings Contemporary Archives. January 1992 </bnc:title>
<par>
Foreign Ministers' meeting
The second meeting of the Council of Foreign Ministers of the Conference on Security and Co-Operation in Europe (CSCE) opened in Prague on Jan. 30-31 &lsqb; for first meeting see p. 38314 &rsqb;.
The former Soviet republics of <annot><location reading="literal"> Armenia </location></annot>, Azerbaijan, Byelarus, Kazakhstan, Kirgizstan, Moldova, Turkmenistan, Tajikistan, Uzbekistan and Ukraine were admitted as new members on Jan. 30, with Russia taking over the Soviet Union's seat, bringing the total number of CSCE members to 48.
(The Baltic states of Estonia, Latvia and Lithuania had been admitted as full members in September 1991 &mdash; see p. 38458.)
</par>
<label>met</label>
</sample>

<sample id="samp1005">
<bnc:title> Keesings Contemporary Archives. Feburary 1990 </bnc:title>
<par>
Inflation rate 12% (1988)
Unemployment 12% (1987 est.)
Principal trading partners (1988) Exports: USA (41%), El Salvador, West Germany; Imports: USA (39%), Mexico, <annot><location reading="literal"> Japan </location></annot>
New economic programme
</par>
<label>met</label>
</sample>

<sample id="samp1006">
<bnc:title> Computergram international </bnc:title>
<par>
VERBEX GIVES VOICE TO UNIX
Verbex Voice Systems Inc, Edison, <annot><location reading="literal"> New Jersey </location></annot> has a speech system for Unix System V.4.2 and Solaris 1.X.
The Speech Commander Desktop co-processor with signal processing includes a developers toolkit for creating speech interfaces under Unix and interfaces to workstations and personal computers over RS232 connections: prices go from &dollar;2,800.
</par>
<label>lit</label>
</sample>

<sample id="samp1007">
<bnc:title> The daily mirror </bnc:title>
<par>
Hundreds of women and children were left behind.
The racket was exposed at a refugee centre in Croatia.
<annot><location reading="metonymic" metotype="place-for-people" notes="OFF"> Britain </location></annot> and America are close to agreeing the best way of protecting relief supplies to Bosnia, Foreign Secretary Douglas Hurd said yesterday.
Starved
</par>
<label>met</label>
</sample>

<sample id="samp1008">
<bnc:title> Keesings Contemporary Archives. June 1990 </bnc:title>
<par>
Lee visited Hong Kong in January 1990, when he expressed doubts about the feasibility of introducing democratic structures before assimilation by China in 1997.
The &quot; one country, two systems &quot; concept agreed by China was based on Hong Kong's colonial administration system rather than on parliamentary democracy, he warned.
Taken along with his restrained reaction to the repression of the pro-democracy movement in China itself &lsqb; see pp. 36720-22 &rsqb;, his attitude gave rise to some suggestions that he saw a role for himself as a potential mediator in the <annot><location reading="metonymic" metotype="place-for-event"> Hong Kong </location></annot> issue.
</par>
<label>met</label>
</sample>

<sample id="samp1009">
<bnc:title> Keesings Contemporary Archives. Feburary 1990 </bnc:title>
<par>
The Thai-Myanma Regional Co-ordinating Committee, made up of senior military officers from both countries, held its first meeting in the northern Thai town of Chiang Mai on Sept. 18-20, 1989.
Problems along their common border were discussed.
Relations with China and <annot><location reading="literal"> Singapore </location></annot>
A 24-member Myanma delegation led by Army Commander-in-Chief Gen. Tan Shwe visited China on Oct. 18-27, 1989.
</par>
<label>met</label>
</sample>

<sample id="samp1010">
<bnc:title> Keesings Contemporary Archives. July 1992 </bnc:title>
<par>
EUROPE
<annot><location reading="literal"> FINLAND </location></annot>
Visit by Yeltsin
</par>
<label>lit</label>
</sample>

<sample id="samp1011">
<bnc:title> GlenPatrick News </bnc:title>
<par>
There followed a few years of growth with turnover increasing from &pound;11 million 1982 to &pound;18 million in 1987.
The workforce grew to 500.
BMK became the first carpet manufacturer in <annot><location reading="literal"> Britain </location></annot> to be registered with the 1987 version of British Standard 5750 for Quality Assurance.
In 1992 BMK was purchased by Stoddard Sekers International.
</par>
<label>lit</label>
</sample>

<sample id="samp1012">
<bnc:title> &lsqb;Independent, electronic edition of 19891013; Foreignmaterial&rsqb; </bnc:title>
<par>
On one level the sudden and unexpected friendship thrives on little more than mutual back-scratching.
When most countries recoiled in horror at China's killing of unarmed protesters four months ago, East Berlin helped break China's isolation by offering support and congratulations.
Likewise, when China had trouble getting guests for its national day celebrations on 1 October, the 40th anniversary of Communist rule, East Germany was again glad to oblige, along with hardline stalwarts such as <annot><location reading="metonymic" metotype="place-for-people" notes="OFF"> Cuba </location></annot>, North Korea, Czechoslovakia and three African countries: the Comoros, Kenya and Burundi.
In its zeal to relieve China's embarrassment at hosting a party with so few guests, East Berlin sent two senior officials &mdash; Egon Krenz, a member of the Politburo, and Wolfgang Rachfuss, a member of the Central Committee.
</par>
<label>met</label>
</sample>

<sample id="samp1013">
<bnc:title> The Dictionary of National Biography$1$1$2Missing persons &lsqb;Part 20 of 20&rsqb; </bnc:title>
<par>
They had seven children.
Following a second stroke in 1892 he retired, and he died 15 June 1893 in Torquay.
&lsqb; Henry Housman, John Ellerton, 1896; John Julian, Dictionary of Hymnology, revised edn., 1907; J. R. Watson, &bquo; The day thou gavest &equo;, Bulletin of the Hymn Society of <annot><location reading="literal"> Great Britain </location></annot> and Ireland, vol. x, no. 158, 1983, p. 144; B. Braley, Hymnwriters 1, 1987. &rsqb;
</par>
<label>lit</label>
</sample>

<sample id="samp1014">
<bnc:title> Last man to die </bnc:title>
<par>
The captain had explained it to every man in the crew over the intercom.
&bquo; We've come this far together; you have a right to know what to expect. &equo;
They would be rendezvousing with the two other U-boats &mdash; if they weren't already at the bottom of the North Sea &mdash; just off the southern coast of <annot><location reading="literal"> Norway </location></annot>.
It was Germany's doorstep; there was no other route home, and that's where the British forces would be waiting.
</par>
<label>lit</label>
</sample>

<sample id="samp1015">
<bnc:title> The emergence of modern Japan </bnc:title>
<par>
Economic growth has occurred within a framework of close ties with the US and membership of the capitalist camp.
At home a constitutional commitment to democracy has resulted in an almost unbroken dominance of conservative political parties.
<annot><location reading="literal"> Japan </location></annot>'s pivotal role in the world economy has provoked a search for the reasons why Japan's economy has continued to prosper in the face of a lack of natural resources and a high degree of dependence on international trade.
Both developed and developing countries have sought to learn from Japan's experience.
</par>
<label>met</label>
</sample>

<sample id="samp1016">
<bnc:title> New scientist </bnc:title>
<par>
Every morning we woke to find ourselves surrounded by fresh tracks made by capybaras (the world's largest species of rodent, looking something like a giant guinea pig); on our last evening, the boatman killed an alligator as it crawled past our camp-fire to go hunting in the reeds beyond.
Every few minutes down the river we would see a wild cocoa tree on the bank, and exploring in the forest behind we usually found many more trees.
Only a few of these had pods, but here and elsewhere we found enough pods to make an important observation: all the wild cocoa throughout the Amazon region of <annot><location reading="literal"> Ecuador </location></annot> shares a common set of genetically determined characteristics including white seeds, very rough-surfaced yellow pods, and the absence of red pigmentation in the leaves.
As these features are not found together in any group of cocoa varieties already in cultivation, this is definite evidence that we have added some new genes to the &bquo; gene pool &equo; of cultivated cocoa.
</par>
<label>lit</label>
</sample>

<sample id="samp1017">
<bnc:title> The Enviroment Digest September 1990 </bnc:title>
<par>
Some of the poorer members felt their chances of &quot; catching up &quot; economically with the rest of the Community would be hampered by heavy carbon taxes.
Contrary to some expectations, however, Greece supported environmental taxes.
<annot><location reading="metonymic" metotype="place-for-people" notes="OFF"> The Netherlands </location></annot> disagreed because it thought harmonised taxes would be too weak.
The country has ambitious plans for environmental tax incentives and other financial incentives &lsqb; see below &rsqb;.
</par>
<label>met</label>
</sample>

<sample id="samp1018">
<bnc:title> England versus West Indies </bnc:title>
<par>
Barbados, which even now has little more than a quarter of a million people, has led the way with a roll of honour of mind-boggling proportions.
Trinidad, which now has around a million inhabitants, has also produced far more than its fair share, and it is interesting to note the differences between the two.
In <annot><location reading="literal"> Barbados </location></annot> (and other places such as Jamaica and Antigua), the wickets are fast and so the bowlers have traditionally bowled fast, while the batsmen have looked to attack at every opportunity, to hit the ball as hard and as gleefully as possible.
Trinidad, on the other hand, used matting wickets for decades, producing batsmen who relied on timing and placing for their runs rather than power, men such as Stollmeyer and, more recently, Gomes, who were closer in style to their English opponents than to some of their team-mates.
</par>
<label>lit</label>
</sample>

<sample id="samp1020">
<bnc:title> Liberating communications </bnc:title>
<par>
The post-1940s policy consensus in Britain, argues Hall, involved the trade unions and management, as well as the central government.
Consensus was of a rather passive kind and policy tended to rely on very general financial guidelines operated by the Bank of England and the Treasury; financial aid to industry was confined to regional development aid.
In <annot><location reading="literal"> France </location></annot>, by contrast, post-1940s reconstruction was marked by extensive nationalization accompanied by state planning.
The national policy consensus excluded the trade unions; the alliance of government agencies and certain companies was more activist than in Britain; planning goals were pursued with a battery of penalty and incentive powers.
</par>
<label>lit</label>
</sample>

<sample id="samp1021">
<bnc:title> The economist </bnc:title>
<par>
The sacrifice
FROM OUR SOUTH KOREA CORRESPONDENT
ACCORDING to the rules that govern <annot><location reading="literal"> South Korea </location></annot>'s annual outbreak of student protests, it should be just about time for petrol bombs to give way to more agreeable activities.
But the unusual intensity of this year's protests has left both the students and the government wondering about the price of peace.
</par>
<label>lit</label>
</sample>

<sample id="samp1022">
<bnc:title> &lsqb;Title unknown/unassigned&rsqb; </bnc:title>
<par>
In his case, the court voted four to three to uphold his conviction on appeal, which is very close. &equo;
He is still optimistic that Richey's conviction will be overturned, but the case could drag on for another six years or more.
Mr Stafford Smith is one of four lawyers who work at the Southern Centre for Human Rights in Atlanta, <annot><location reading="literal"> Georgia </location></annot>, which is the only office of defence lawyers funded solely by private contributions.
Four years ago there was no-one to defend the accused except state lawyers.
</par>
<label>lit</label>
</sample>

<sample id="samp1024">
<bnc:title> Running </bnc:title>
<par>
That pace suited Marot, but not Rasmussen.
&bquo; At one point I thought about stopping, &equo; Rasmussen said, &bquo; but that would have been a first for me, because I've never dropped out of a marathon. &equo;
Marot won comfortably in 2:30:55; Rasmussen finished two minutes later, in 2:32:58 with Olga Appell of <annot><location reading="literal"> Mexico </location></annot> taking third place in a time of 2:33:18.
</par>
<label>lit</label>
</sample>

<sample id="samp1025">
<bnc:title> &lsqb;Title unknown/unassigned&rsqb; </bnc:title>
<par>
&bquo; We plan a major show of force in the Kismayu region over the next few days, &equo; Col Peck said.
He had no specific details of an offensive by Mr Jess.
The <annot><location reading="literal"> US </location></annot> military's Radio Rajo reported that forces loyal to Mr Jess appeared to be moving nearer to Kismayu, dominated by supporters of Mohamed Said Hersi, known as Gen Morgan.
Col Peck said Belgian troops based in Kismayu had already launched extensive patrols north and south of the port.
</par>
<label>lit</label>
</sample>

<sample id="samp1026">
<bnc:title> Keesings Contemporary Archives. August 1990 </bnc:title>
<par>
&lsqb; See p. 37620 for Waldheim's informal meeting in July 1990 with President Havel of Czechoslovakia and President von Weizs&auml;cker of West Germany. &rsqb;
Immigration restrictions
During 1989 a total of 21,882 people, nearly twice as many as in 1988 and most of them from Eastern Europe, sought asylum in <annot><location reading="literal"> Austria </location></annot>, and during the first three months of 1990 the numbers reached 5,000, most of them being Romanians who were arriving at a rate of 200 per day in late February.
The government with effect from March 15 imposed restrictions at its border with Hungary to slow down the inflow of East Europeans.
</par>
<label>lit</label>
</sample>

<sample id="samp1027">
<bnc:title> Keesings Contemporary Archives. Feburary 1991 </bnc:title>
<par>
BANGLADESH
General election
A general election held in <annot><location reading="literal"> Bangladesh </location></annot> on Feb. 27 was dominated by the Bangladesh Nationalist Party (BNP) and the Awami League, both of which had boycotted the previous elections held in March 1988 &lsqb; see pp. 35835-36 &rsqb;.
The elections had been called in mid-December 1990 after student protestors and the opposition parties had forced the resignation of the President, Lt.-Gen. (retd) Hussain Mohammed Ershad &lsqb; see pp. 37906-07 &rsqb;.
</par>
<label>lit</label>
</sample>

<sample id="samp1028">
<bnc:title> Today </bnc:title>
<par>
FINAL SCORES: 274: N Faldo (GB) 68, G Norman (Aus) 63.
Faldo won at first extra hole.
283: D Love (US) 66, T Kite (US) 70. 284: I Woosnam (GB) 68. 285: M Roe (GB) 70. 287: F Couples (US) 73. 288: D Edwards (USA) 70, R Floyd (<annot><location reading="literal"> US </location></annot>) 70, T Johnstone (Zim) 67. 289: P Azinger (US) 67.
Other: 291: C Montgomerie (GB) 70. 292: S Lyle (GB) 70. 295: C O'Connor jnr (GB) 75. 296: B Langer (Ger) 71. 301: B Lane (GB) 74. 304: A Forsbrand (Swe) 81. 306: S Ballesteros (Sp) 75.
</par>
<label>lit</label>
</sample>

<sample id="samp1029">
<bnc:title> Problems of unemployment and inflation </bnc:title>
<par>
The duration of unemployment in the <annot><location reading="literal"> UK </location></annot> and unemployment flows
A series of statistics published in the Employment Gazette provides information about monthly flows into and out of the pool of unemployment and these enable more accurate calculations of the average duration of unemployment spells to be made.
</par>
<label>lit</label>
</sample>

<sample id="samp1030">
<bnc:title> THE PENGUIN HISTORY OF GREECE </bnc:title>
<par>
The Athenians (we quote from Thucydides now) &bquo; brought home their women and children and the possessions they had saved &hellip; and prepared to rebuild their city and walls; for not much of the perimeter was standing, and most of the houses were down.
only a few surviving, in which the Persian grandees had lodged &equo;.
But the Spartans, prompted by Corinth and Aigina. both now thoroughly afraid of Athens' huge naval power, sent an embassy to demur, urging that fortified towns outside the Peloponnese might be of use to the enemy if he came again, and that the Peloponnese itself was the best citadel for all <annot><location reading="metonymic" metotype="place-for-people" notes="POP"> Greece </location></annot>.
On the motion of Themistokles, the Athenians got rid of them with a promise to confer.
</par>
<label>met</label>
</sample>

<sample id="samp1031">
<bnc:title> Keesings Contemporary Archives. August 1991 </bnc:title>
<par>
Branko Salaj was later appointed Information Minister.
Meeting of Pentagonale / Hexagonale grouping